import Head from "next/head";
import Image from "next/image";
import Hero from "../components/Hero";
import NavBar from "../components/NavBar";
import { useSession, signIn, signOut } from "next-auth/react";

export default function Home() {
  const { data: session } = useSession();
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      {!session ? <Hero/> : (<div>
      <button className="btn btn-primary" onClick={() => signOut()}><span className="flex flex-row gap-x-1 items-center">Log out</span></button>
        
        </div>)}
    </div>
  );
}
